In [2]:
import numpy as np

In [33]:
#BMI using numpy 
height = [5,3,6,2,9]
weight = [53,53,76,82,79]
np_height = np.array(height)
np_weight = np.array(weight)

In [36]:
bmi = np_weight / np_height ** 2

In [37]:
bmi

array([ 2.12      ,  5.88888889,  2.11111111, 20.5       ,  0.97530864])

In [38]:
np_weight

array([53, 53, 76, 82, 79])

In [39]:
weight

[53, 53, 76, 82, 79]

In [41]:
bmi > 10

array([False, False, False,  True, False])

In [42]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [43]:
aaa = np.array(baseball) * 2
aaa

array([360, 430, 420, 420, 376, 352, 418, 400])

In [45]:
x = ["a", "b", "c"]
x[1]



'b'

In [46]:
np_x = np.array(x)
np_x[1]

'b'

In [50]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
a=np_mat * 2
b=np_mat + np.array([10, 10])
c=np_mat + np_mat

print(np_mat)
print(a)
print(b)
print(c)

[[1 2]
 [3 4]
 [5 6]]
[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [52]:
import numpy as np
x = [1, 4, 8, 10, 12]
mean = np.mean(x)
median = np.median(x)

print(mean)
print(median)

7.0
8.0


In [3]:
import numpy as np
a = np.array(['ali','husain','kashif','arslan'])
b = np.array([1,3,4,6])
print(b[a == 'kashif'])

[4]


In [4]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

areas

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5]